# Generated by Django 2.0.7 on 2018-07-22 19:16

from django.db import migrations, models
import django.db.models.deletion
import geoposition.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(help_text='Enetr Client Name Here, Max 40 Chars', max_length=40, verbose_name='Client Name')),
                ('client_email', models.EmailField(help_text='Enter Client Email Here', max_length=40, verbose_name='Client Email')),
                ('client_phone', models.CharField(help_text='Enter Client Phone Number Here, Do not include +88', max_length=15, verbose_name='Client Phone')),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_code_name', models.CharField(help_text='Enter The Device Codename, Max 40 Chars(E.G. DBBL-1209-01)', max_length=40, verbose_name='Client Name')),
                ('position_address', models.CharField(help_text='Enter The Device Location Address, Max 40 Chars(E.G. 322, Concept Tower, Panthopath, Dhaka - 1209)', max_length=40, verbose_name='Client Name')),
                ('position', geoposition.fields.GeopositionField(max_length=42)),
                ('device_ip', models.GenericIPAddressField()),
                ('client_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.Client')),
            ],
        ),
    ]
