# Generated by Django 2.0.7 on 2018-07-22 19:40

from django.db import migrations, models
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='device_port',
            field=models.PositiveIntegerField(null=True, verbose_name='ABC'),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_code_name',
            field=models.CharField(help_text='Enter The Device Codename, Max 40 Chars(E.G. DBBL-1209-01)', max_length=40, verbose_name='Device Codename'),
        ),
        migrations.AlterField(
            model_name='device',
            name='position',
            field=geoposition.fields.GeopositionField(help_text='Enter Lattitude and Longitude Here, Please Select from Map', max_length=42),
        ),
        migrations.AlterField(
            model_name='device',
            name='position_address',
            field=models.CharField(help_text='Enter The Device Location Address, Max 100 Chars(E.G. 322, Concept Tower, Panthopath, Dhaka - 1209)', max_length=100, verbose_name='Device Position Address'),
        ),
    ]
