# Generated by Django 2.0.7 on 2018-09-06 22:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20180906_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='guard',
            name='Schedule Time - From',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guard',
            name='Schedule Time - to',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
