# Generated by Django 2.0.7 on 2018-09-06 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20180906_2213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guard',
            old_name='Schedule Time - to',
            new_name='Schedule Time - To',
        ),
    ]
