# Generated by Django 2.1.1 on 2018-09-08 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_notificationlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationlog',
            name='sensor_value',
            field=models.CharField(default='None', help_text='From Which Sensor the Inrusion Occured', max_length=100),
        ),
    ]
