# Generated by Django 2.1.1 on 2018-09-08 20:12

from django.db import migrations
import django_geoposition_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20180908_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='position',
            field=django_geoposition_field.fields.GeopositionField(help_text='Enter Lattitude and Longitude Here, Please Select from Map', max_length=100),
        ),
    ]
