# Generated by Django 2.1.1 on 2018-09-08 20:28

from django.db import migrations
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20180908_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='position',
            field=geoposition.fields.GeopositionField(help_text='Enter Lattitude and Longitude Here, Please Select from Map', max_length=42),
        ),
    ]
