# Generated by Django 2.1.1 on 2018-09-08 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_auto_20180908_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='lattitude',
            field=models.DecimalField(decimal_places=10, default=123.123, help_text='Posision', max_digits=100, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='longitude',
            field=models.DecimalField(decimal_places=10, default=123.123, help_text='Posision', max_digits=100, null=True),
        ),
    ]
