# Generated by Django 2.1.1 on 2018-09-08 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_device_device_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='inactive', help_text='Do You Want To Accept Data From This Device?', max_length=10, verbose_name='Device Status'),
        ),
    ]
