# Generated by Django 2.1.1 on 2018-09-11 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_auto_20180908_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationlog',
            name='notification_status',
            field=models.CharField(default='false', help_text='Notification Type', max_length=10),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='sensor_name',
            field=models.CharField(help_text='From Which Sensor the Inrusion Occured', max_length=100),
        ),
    ]
