# Generated by Django 2.1.1 on 2018-09-11 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_auto_20180911_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationlog',
            name='notification_status',
            field=models.CharField(choices=[('false', 'False Alarm'), ('warning', 'Warning'), ('intrusion', 'Intrusion')], default='false', help_text='Notification Type', max_length=10),
        ),
    ]
