# Generated by Django 2.1.1 on 2018-09-11 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_auto_20180911_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationlog',
            name='notification_status',
            field=models.CharField(choices=[('monitor', 'Monitor'), ('false', 'False Alarm'), ('warning', 'Warning'), ('intrusion', 'Intrusion')], default='monitor', help_text='Notification Type', max_length=10),
        ),
    ]
